### ISSUE TITLE
problem with ipysigma

### ISSUE THREAD

**Issue by liutf2005** [Yomguithereal/ipysigma#1]
Hi ，

I followed the example and found that I cannot display the network properly. 

All I got is something like this "Sigma(data={'nodes': [(0, {'club': 'Mr. Hi'}), (1, {'club': 'Mr. Hi'}), (2, {'club': 'Mr. Hi'}), (3, {'club': …".  And no picture is displayed.

Did I miss something？

**Comment by Yomguithereal** [comment]
Did you run

```
jupyter nbextension enable --py --sys-prefix ipysigma
```

after installing the lib?

**Comment by liutf2005** [comment]
Yes.

And when I opened "https://github.com/Yomguithereal/ipysigma/blob/master/notebooks/Examples.ipynb",  I got the same result.

**Comment by liutf2005** [comment]
Interesting.

It works fine now：）

**Comment by Yomguithereal** [comment]
Yes it is possible. Can you open a related issue so I remember to add this later?
