### ISSUE TITLE
Unable to render outside of a notebook context

### ISSUE THREAD

**Issue by cpsievert** [Yomguithereal/ipysigma#18]
The [suggested way](https://ipywidgets.readthedocs.io/en/stable/embedding.html#python-interface) of getting standalong HTML from ipywidgets doesn't appear to work:

```python
import networkx as nx
from ipysigma import Sigma

karate_club = nx.karate_club_graph()
w = Sigma(karate_club)

from ipywidgets.embed import embed_minimal_html
embed_minimal_html("index.html", w)
```

```shell
$ python3 -m http.server
```

<img width="920" alt="Screen Shot 2021-11-30 at 9 50 58 AM" src="https://user-images.githubusercontent.com/1365941/144080706-f0c79102-368f-48c8-ae9c-08501ee40062.png">

**Comment by Yomguithereal** [comment]
@cpsievert I don't really know how to make this widget embeddable as raw html without requiring to massively fatten your `.ipynb` file or the resulting html output. What's more, ipywidgets specs were evolving very fast when I wrote the widget so it might have changed. But if you have some knowledge in the matter you can probably help me find a solution.
